# Generated by Django 3.1.3 on 2020-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201205_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default='this is a default summary', max_length=280),
            preserve_default=False,
        ),
    ]
